# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "garmin_connectr"
  s.version = "0.0.8"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["aroth"]
  s.date = "2012-01-27"
  s.description = "GarminConnectr is a simple Ruby library for accessing data from Garmin Connect."
  s.email = "adamjroth@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".gemspec",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "examples/activity.rb",
    "examples/activity_list.rb",
    "features/activity.feature",
    "features/activity_list.feature",
    "features/step_definitions/activity_list_steps.rb",
    "features/step_definitions/activity_steps.rb",
    "features/support/env.rb",
    "garmin_connectr.gemspec",
    "lib/garmin_connectr.rb",
    "test/garmin_connectr_test.rb"
  ]
  s.homepage = "http://github.com/aroth/garmin_connectr"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.15"
  s.summary = "GarminConnectr is a simple Ruby library for accessing data from Garmin Connect."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

